alg = (input('Digite algo na tela: '))
print('O numero digitado foi {}'.format(alg))
print(type(alg))
print('É alfabetico: ')
print(alg.isalpha())
print('É numerico:')
print(alg.isnumeric())
print('É alfanumerico:')
print(alg.isalnum())
print('É escrito em maiusculas:')
print(alg.isupper())
print('É escrito em minusculas:')
print(alg.islower())
